name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  format:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cargo
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cargo
          version: 1.0

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install typstyle
        run: cargo binstall --no-confirm typstyle@0.15.1

      - name: Check formatting
        run: typstyle --check src tests

  test:
    name: Typst ${{ matrix.typst }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { typst: 0.13.1, tytanic: 0.2.2, compare: false }
          - { typst: 0.14.2, tytanic: 0.3.4, compare: false }
          - { typst: 0.15.1, tytanic: 0.4.1, compare: true }
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install cargo
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: cargo
          version: 1.0

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install tytanic
        run: cargo binstall --no-confirm tytanic@${{ matrix.tytanic }}

      - name: Run tests
        run: tt run --no-fail-fast ${{ matrix.compare && '' || '--no-compare' }}

      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: artifacts-${{ matrix.typst }}
          path: |
            tests/**/diff/*.png
            tests/**/out/*.png
            tests/**/ref/*.png
          retention-days: 14
